name: Lint, Test and Build Production App Version
run-name: Checking ${{ github.actor }} code and creating a production build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Lint-Test-Build_Prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9.1.2'
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          cache: 'pnpm'
      - name: Install App Dependencies And Build Production App Version
        run: pnpm build:cicd
      - name: Lint TS
        run: pnpm lint
      - name: Test Unit
        run: pnpm test
      - name: Test E2E
        run: pnpm test:e2e